### ISSUE TITLE
random.randint

### ISSUE THREAD

**Issue by dontreallyusethis** [amirmaula/lycabot#1]
for letter in first_name:
    time.sleep(random.randint(0, 1))  # sleep between 1 and 3 seconds
    elem_form_first_name.send_keys(first_name)

It's time.sleep(random.randint(0, 1))

**Comment by amirldn** [comment]
I think the issue here is that I wrote elem_form_first_name.send_keys(first_name)

It should have been elem_form_first_name.send_keys(letter)

I shall update and fix this now.

**Comment by amirldn** [comment]
Fixed

**Comment by dontreallyusethis** [comment]
Where can I contact you?

I would like to report something else.

**Comment by amirldn** [comment]
You can contact me through my email at amirmaula@outlook.com
